language: python
python:
  - "3.6"
service:
  - postgresql
# command to install dependencies
before_install:
  - export FLASK_APP=run.py
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database test_db;' -U postgres
# command to run tests
script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls
