language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flask
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below